sudo: true
dist: trusty

before_install:
- openssl aes-256-cbc -K $encrypted_85c67507a308_key -iv $encrypted_85c67507a308_iv -in deploy.enc -out deploy -d
- chmod 600 deploy
- mv deploy ~/.ssh/id_rsa
script:
  - binaries/hugo
after_success:
  - rsync -avz -e "ssh -i $HOME/.ssh/id_rsa" --progress --delete public/ ${deploy_user}@${deploy_host}:~/${deploy_path}