sudo: true
dist: trusty

before_install:
- openssl aes-256-cbc -K $encrypted_85c67507a308_key -iv $encrypted_85c67507a308_iv -in deploy.enc -out deploy.key -d
- chmod 600 deploy.key
script:
  - binaries/hugo
after_success:
  - rsync -avz -e "ssh -i deploy.key -o 'StrictHostKeyChecking no'" --progress --delete public/ ${deploy_user}@${deploy_host}:${deploy_path}
  - rm deploy.key