baseurl = "/"
title = "Thomas Gray"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-cog"
  copyright = "Thomas Gray 2018"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/tgrayprojects/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/tgray-projects"

title = "Dimension"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
