baseurl = "/"
title = "Thomas Gray"
theme = "dimension"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Homesteading on a small farm on the west coast of Canada, living in an area known locally as "Paradise Valley" on the Sunshine Coast while telecommuting on a fibre internet connection.  Troubleshooting code and tractors in equal parts some days.<!--]--><br /><br />
                <!--[-->But mostly, I love technology.<!--]-->'
  logo = "fa-cog"
  copyright = "Thomas Gray 2018"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/tgrayprojects/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/tgray-projects"